version: "2"
services:
  webdriverio:
    build:
      dockerfile: dockerfile
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./app:/app
    networks:
      - default

  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - default

  firefox:
    image: selenium/node-firefox
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    depends_on:
      - hub
    networks:
      - default

  chrome:
    image: selenium/node-chrome
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    depends_on:
      - hub
    networks:
      - default

networks:
  default:
